### ISSUE TITLE
Request: Add Color Transition

### ISSUE THREAD

**Issue by CliffCawley** [RubenGees/Introduction#10]
Would be great to have an option that supports Color Transition as you're changing between pages.

Something like from here: http://www.thedroidsonroids.com/blog/android/how-to-create-fancy-screen-transitions-used-in-walkthrough-in-android-google-drive-app/

Under the 'Color Transition' section.

**Comment by rubengees** [comment]
Looks good! I'll take a look.

**Comment by rubengees** [comment]
The latest version now supports a Transformer for color transitions: https://github.com/rubengees/introduction/releases/tag/1.3.1
See the latest sample and this [wiki page](https://github.com/rubengees/introduction/wiki/Custom-Transformer) for infos on how to do that.

**Comment by CliffCawley** [comment]
<3

**Comment by CliffCawley** [comment]
Awesome, just implemented it according to your wiki, works fantastic and looks so stylish! Thanks for implementing it so fast! :+1:

**Comment by rubengees** [comment]
No problem!
