### ISSUE TITLE
RTL support 

### ISSUE THREAD

**Issue by mohammedhammouri** [RubenGees/Introduction#12]
- [checked] **I have verified that I am using the latest version and searched for exisiting issues** (If this checkbox is not ticked, the issue might be ignored).

I am using version: 1.3.7 
My device (if relevant) is: multiple devices  
It runs `Android` version (if relevant): 4.1 - 7.0  

##### This is what happens:

When using RTL device on 4.3 or above
The back and next buttons are reversed (Just adding drawable-rtl) will fix it I think

When using RTL device on below 4.3 
The buttons come on top of each other 
adding start and end with right and left I think will fix the problem 
Thanks 
   
![screenshot_20170224-140037](https://cloud.githubusercontent.com/assets/6051190/23303007/2e45ed6c-fa9a-11e6-8e24-f569d70309c9.png)

![whatsapp image 2017-02-24 at 2 06 18 pm](https://cloud.githubusercontent.com/assets/6051190/23303119/de6a66fa-fa9a-11e6-928a-c71b8e96fdc5.jpeg)

**Comment by rubengees** [comment]
Good catch, I will investigate that shortly!

**Comment by rubengees** [comment]
Released as [1.3.9](https://github.com/rubengees/introduction/releases/tag/1.3.9).
It should work out of the box. Please let me now if it works for you!

**Comment by mohammedhammouri** [comment]
Thanks, It works :D 
Very fast response :D
