### ISSUE TITLE
Unable to find explicit activity class 

### ISSUE THREAD

**Issue by riadhnet** [RubenGees/Introduction#14]
**Please check if you are running the latest version and there are no existing Issues for your problem. Delete this line when submitting the Issue.**

I am using version: 1.4.1
My device (if relevant) is:  Galaxy s5
It runs `Android` version (if relevant): 6.0.1

#### This is what happens:
RuntimeException
Unable to find explicit activity class 
{com.test.app/com.rubengees.introduction.IntroductionActivity}; have you declared this activity in your AndroidManifest.xml?

Any reason for this to happen ? 

i'm calling like this
    new IntroductionBuilder(this)
                .withSlides(generateSlides())
                 .withPreviousButtonEnabled(false)
                .withAllowBackPress(false)
                .withForcedOrientation(IntroductionBuilder.ORIENTATION_PORTRAIT)
                .withStyle(new CustomIntroStyle())
                .introduceMyself();

**Comment by riadhnet** [comment]
Fixed using this to manifest
       <activity android:name="com.rubengees.introduction.IntroductionActivity"/>
it's not mentioned in the documentation

**Comment by rubengees** [comment]
That should not happen, it is present in the libraries `Mainfest`.
Are you using `Gradle`? If yes, does `compile 'com.github.rubengees:introduction:1.4.1@aar'` work?

**Comment by riadhnet** [comment]
yes i have tried ` compile('com.github.rubengees:introduction:1.4.1@aar') {
        transitive = false;
    }`

and `compile 'com.github.rubengees:introduction:1.4.1@aar'`
