### ISSUE TITLE
Is this really API 11?  Could it go lower?

### ISSUE THREAD

**Issue by fat-tire** [RubenGees/Introduction#4]
Cool project!  This looks like it may help a lot of people who have to deal with the new permissions model..

I notice that the library dependencies seem to be SDK 8 (froyo)... Just perusing the code here I didn't see anything in build.gradle specifying a minimum sdk level-- is there some reason why it's [listed as being for sdk 11](https://android-arsenal.com/details/1/2498)?

**Comment by rubengees** [comment]
I use a method at one place which is sdk 11+ only. I think it is possible to do it otherwise, will have a look.

**Comment by rubengees** [comment]
It's sdk 10 now, the min of the 2 libs in this project.

**Comment by rubengees** [comment]
https://github.com/RubenGees/Introduction/releases/tag/v1.0.5
