### ISSUE TITLE
Enhancement Request: Skip Button/Build Problems

### ISSUE THREAD

**Issue by Trek333** [RubenGees/Introduction#8]
Rubengees,

No Skip button feature could be found inthe Wiki for the Introduction library. Would it be possible to add a Skip Button to add Slides to allow the user to exit more easily?

Thanks,
Jeff

**Comment by rubengees** [comment]
Yes it is not in now, I will look into it.

**Comment by rubengees** [comment]
https://github.com/rubengees/introduction/releases/tag/1.1.5
Take a look if the `withSkipEnabled(String text)` and `withSkipEnabled(int resource)` methods fit your expectations.

**Comment by Trek333** [comment]
Thanks for quick response. It may take me a few days to try it. I ran into an unrelated issue that I have been unable to resolve with an Android library. See Android Issue 198963 (https://code.google.com/p/android/issues/detail?id=198963) if interested.

**Comment by Trek333** [comment]
I appreciate the adding of the Skip button, but my app is compiled for API 10 and above which is one of the main reasons that I chose the Introduction library. Per the url in your last message that by adding the skip button, API 11 or above is now required. Any possibility to keep the API requirements to 10 or above?

**Comment by rubengees** [comment]
It should not. I can compile release 1.1.5 with api 10. 
What is the error message or the relevant code?

**Comment by rubengees** [comment]
Ahh you mean 'Animations for the previous and next button on Api >= 11' ?
That only means that for Api >= 11 there will be animations and lower than that there are simply none, but works nevertheless.

**Comment by Trek333** [comment]
I tried to add the withSkipEnabled method to my Android Studio project, but Android Studio does not find it. I can see the following code at this url https://github.com/rubengees/introduction/blob/master/library/src/main/java/com/rubengees/introduction/IntroductionBuilder.java

```
@NonNull
public IntroductionBuilder withSkipEnabled(@NonNull String text) {
    this.skipString = text;
    this.skipResource = null;

    return this;
}
```

I tried to build the project anyways, and I got the following with error. It appears that the Introduction library has not been updated yet on the GitHub website yet.

Error:(400, 17) error: cannot find symbol method withSkipEnabled(int)

**Comment by rubengees** [comment]
What is in your build.gradle?
Have you upgraded to

``` groovy
compile ('com.github.rubengees:introduction:1.1.5@aar'){
        transitive = true;
}
```

?

**Comment by Trek333** [comment]
My build gradle is pasted below. Do you need to change the version number to allow the changes to be recognized in GitHub because it was 1.1.5 before the addition of Skip button code?

```
compile('com.github.rubengees:introduction:1.1.5@aar') {
    transitive = true;
}
```

**Comment by rubengees** [comment]
Before I added the skip button it was 1.1.4. Now it's 1.1.5. Don't you get the feature with that build.gradle?

**Comment by Trek333** [comment]
No...I can not get the skip button feature to be recognized in Android Studio, but all of the other Introduction library features that I am using works. I have tried the String and resource versions of the method, but neither one works for me. Also, tried using the library in another project, but while the features are recognized by Android Studio, the withSkipEnabled method is not.

```
    result.add(new Slide()
            .withTitle(R.string.slidetitle1)
            .withDescription(R.string.slidedesc1)
            .withColorResource(R.color.orange)
            .withSkipEnabled("Skip")
            .withImage(R.drawable.slide1)); 
```

**Comment by rubengees** [comment]
Very weird. Check the following and report back:
- Delete the .gradle folder in your home directory
- Rebuild your Project in Android Studio (Build -> Rebuild)
- Clone this project and try to run the sample

I also let JitPack rebuild the library, maybe that helps.

**Comment by Trek333** [comment]
I tried the following steps that you suggested, but it did not work.

Delete the .gradle folder in your home directory
Rebuild your Project in Android Studio (Build -> Rebuild)

I am not sure of the meaning of the other 2 suggestions

Clone this project and try to run the sample
I also let JitPack rebuild the library, maybe that helps.

However, I downloaded the zip file of the library and imported it into Android Studio on my system. It appears that you may need to update the Slide.java file with the withSkipEnabled method like the other public methods.

**Comment by rubengees** [comment]
Ah I might know what your problem is. The skip methode is called on the IntroductionBuilder and not on a single Slide. Take a look at the [sample](https://github.com/rubengees/introduction/blob/master/sample/src/main/java/com/rubengees/introductionsample/MainActivity.java#L241-L243).

**Comment by Trek333** [comment]
Thanks pointing in the right direction! It works now. I closed out this enhancement/issue.
