### ISSUE TITLE
withView? in addition to withImage for Slide?

### ISSUE THREAD

**Issue by KennyGoers** [RubenGees/Introduction#9]
I want to add a bit of functionality (kinda like Google Maps first start) to show the icon and links to the privacy document as well as the app requirements, etc). Here is an example, not so much the button, but you get the gist I think.
![start-screen1](https://cloud.githubusercontent.com/assets/429628/13517831/cfc68098-e18c-11e5-8b32-f7f4fffa4317.png)

**Comment by rubengees** [comment]
Hmm should be possible. I'll look into it.

**Comment by rubengees** [comment]
Please take a look if the new version fits your expectations.

**Comment by rubengees** [comment]
I'm closing this now. If anything is wrong feel free to reopen.
